export const quotes = [
  "And I object!  I object! He interrupted me while I was watching 'Ow my balls!'   -Frido Pendajo, Idiocracy 2006",
  '“I may not have gone where I intended to go, but I think I have ended up where I needed to be.” ― Douglas Adams ',
  "“I refuse to answer that question on the grounds that I don't know the answer.” \n ― Douglas Adams ",
  '“I always wanted to be somebody, but now I realize I should have been more specific.”  ― Lily Tomlin',
  '“A clean house is a sign of a wasted life.”  ― Unknown',
  '“Why do they call it rush hour when nothing moves?”  ― Robin Williams',
  "“I don't trust people who do acupuncture. They're back stabbers.”  ― Jarod Kintz",
  "“If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.”  ― J.K. Rowling",
  '“Why do they call it a drive-through if you have to stop?”  ― Steven Wright',
  "“I'm not lazy, I'm just conserving my energy.”  ― Lao Tzu",
  '“You know you’re getting old when you stoop to tie your shoelaces and wonder what else you could do while you’re down there.”  ― George Burns',
  '“Why does a round pizza come in a square box?”  ― George Washington',
  '“Why do we put suits in a garment bag and put garments in a suitcase?”  ― George Carlin',
  '“I’m not a proctologist, but I know an asshole when I see one.” ―  Charles Darwin',
  "\"I don't trust people who don't like tacos. I mean, they're just sandwich turnovers. How can you not like them?\" -Jim Gaffigan",
  '“I have not failed. I’ve just found 10,000 ways that won’t work.”  ― Thomas Edison',
  '“I told my wife she was drawing her eyebrows too high. She looked surprised.”  ― Rodney Dangerfield',
  '“Why do people say ‘heads up’ when you should duck?”  ― Sacagawea',
  '“A diplomat is someone who can tell you to go to hell in such a way that you actually look forward to the trip.”  ― Caskie Stinnett',
  '“Why do we say something is out of whack? What is a whack?”  ― Unknown',
  '“I love deadlines. I like the whooshing sound they make as they fly by.”  ― Douglas Adams',
  "\"I've always said that one of the greatest things about McDonald's is that you always know what you're getting.\"",
  '"The best way to predict the future is to invent it." - Alan Kay',
  '“Why do we play in recitals and recite in plays?”  ― Bill Gates',
  '“Age is an issue of mind over matter. If you don’t mind, it doesn’t matter.”  ― Mark Twain',
  '“I’m not arguing, I’m just explaining why I’m right.”  ― Unknown',
  '“The only true wisdom is in knowing you know nothing.”  ― Socrates',
  '“Do not waste time on things you cannot change or influence.”  ― Epictetus',
  '“Peace comes from within. Do not seek it without.”  ― Buddha',
  '“The happiness of your life depends upon the quality of your thoughts.”  ― Marcus Aurelius',
  '“It is not what happens to you, but how you react to it that matters.”  ― Epictetus',
  '“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”  ― Ralph Waldo Emerson',
  '“You are not your thoughts; you are the awareness behind them.”  ― Eckhart Tolle',
  '“There is no way to happiness; happiness is the way.”  ― Thich Nhat Hanh',
  '“It is not the events of our lives that shape us, but our perception of them.”  ― Epictetus',
  '“The only true source of happiness is within.”  ― Buddha',
  '“The only thing we have control over is our thoughts and actions.”  ― Epictetus',
  '“To live a pure unselfish life, one must count nothing as one’s own in the midst of abundance.”  ― Buddha',
  '“Happiness does not come from external circumstances; it is an inner quality.”  ― Dalai Lama',
  '“Do not seek praise; seek to be worthy of praise.”  ― Seneca',
  '“To be aware of a single shortcoming in oneself is more useful than to be aware of a thousand in someone else.”  ― Dalai Lama',
  '“The mind is everything; what you think, you become.”  ― Buddha',
  '“It is not what happens to us that defines us, but our response to what happens.”  ― Epictetus',
  '“An unexamined life is not worth living.”  ― Socrates',
  '“The only thing necessary for the triumph of evil is for good men to do nothing.”  ― Edmund Burke',
  '"Computers are incredibly fast, accurate, and stupid; humans are incredibly slow, inaccurate, and brilliant; together they are powerful beyond imagination." - Big Bird',
  '“The only true wisdom is knowing you have none.”  ― Socrates',
  '“The greatest glory in living lies not in never falling, but in rising every time we fall.”  ― Nelson Mandela',
  '“A goal without a plan is just a wish.”  ― Antoine de Saint-Exupéry',
  '“The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.”  ― Ralph Waldo Emerson',
  '“If you want to live a happy life, tie it to a goal, not to people or things.”  ― Albert Einstein',
  '“Age is an issue of mind over matter. If you don’t mind, it doesn’t matter.” ― Mark Twain',
  '“The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.” ― Terry Pratchett',
  '“Why do they call it taking a dump? The job of it is not taking.” ― George W. Bush',
  '"The computer was born to solve problems that did not exist before." - Bill Gates',
  '"Artificial intelligence is a tool, not a threat." - Satya Nadella',
  '"The best way to have a good idea is to have a lot of ideas." - Linus Pauling',
  '"Data is not information, information is not knowledge, knowledge is not understanding, understanding is not wisdom." - Clive James',
  '"The greatest challenge in computer science is not to build computers that are powerful enough, but to build ones that are usable." - Jef Raskin',
];
